### ISSUE TITLE
"Missing argument for parameter #5 in call" in 01-IncrementOperatorsSpec.swift 

### ISSUE THREAD

**Issue by valbaca** [mokagio/Swift-Koans#1]
Please see [my reddit post describing my error](http://www.reddit.com/r/swift/comments/2yj5ux/question_why_am_i_getting_missing_arg_error_when/)

**Comment by mokagio** [comment]
Hello, thanks for trying this project.

Unfortunately, I have given much love to this project in a while, and the most likely explanation is that it simply not up to date anymore.

I'll see if I can find some time to look into this in the next couple of days.

:beers:

**Comment by mokagio** [comment]
Hello @valbaca, it's been so long that you probably don't care anymore about this project, but anyway I took some time to update it and make it compile.

To be honest I don't think I will put more work into this project.
